[build-system]
requires = ["setuptools>=72.0", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "treeshapy"
version = "1.0.0"
description = "Python library for the evaluation of tree shape indices based on ete3"
authors = [
    {name="Luise Haeuser", email="luise.haeuser@h-its.org"}
]
readme = {file = "README.md", content-type = "text/markdown"}
#license = {text = "GPL-3.0-or-later"}
license = "GPL-3.0-or-later"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "ete3",
    "legacy-cgi",
    "importlib-resources"
]

[project.optional-dependencies]
docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["treeshapy*"]

[tool.setuptools.package-data]
treeshapy = ["resources/*.json"]

